#pragma once
#define CONFIG_TACH_FEEDBACK_ENABLED 1
#define CONFIG_TACH_SAMPLE_MS 500
#define CONFIG_TACH_PULSES_PER_REV 2
#define CONFIG_TACH_STARTUP_GRACE_MS 1000
#define CONFIG_TACH_STALL_RPM 100
#define CONFIG_TACH_STALL_DEBOUNCE_MS 1000
#define CONFIG_TACH_GLITCH_FILTER_NS 1000
#define CONFIG_TACH_STALL_STOP_FAN 1

